conn.go, conn_linux.go, conn_linux_test.go, conn_others.go, conn_others_test.go
This will add a configuration to netlink.Dial which allows to
netlink groups during bind.
=> Add dial configuration

conn.go, conn_linux_test.go, conn_test.go
While working on generic netlink, I discovered that it would probably be a little bit awkward to have the caller keep checking for errors in some functions.  For example, in `genetlink.Conn.Receive`, I was getting an error that a generic netlink header was invalid.  This was because there was a netlink error preceding it, and I wasn't able to check it without calling `Validate`, which meant passing the previous request as a parameter to `Receive`.
As you can see, this got pretty hairy pretty quickly.  I think it probably makes the most sense to just do the validation directly in `netlink.Conn.Receive` so that it can be bubbled up helpfully to any packages wrapping the base one.
=> conn: check for netlink errors in Conn.Receive instead of Validate

genetlink/conn.go, genetlink/conn_linux_test.go, genetlink/conn_test.go, genetlink/doc.go, genetlink/message.go, genetlink/message_test.go
It works!  I think generic netlink is small and simple enough that it's probably okay to include in this repository.  Worst case, it gets split out into its own.
=> genetlink: initial commit

conn.go, conn_linux_test.go, conn_test.go, message.go
Should be nicer than making higher level clients deal with these.
=> conn: support multi-part messages in Receive

genetlink/conn_linux_test.go
=> genetlink: fix integration test for Travis

nlenc/string.go, nlenc/string_test.go
Will need these helpers for generic netlink things.
=> nlenc: add Bytes and String functions

genetlink/conn.go, genetlink/conn_linux_test.go, genetlink/conn_test.go, genetlink/family.go
=> genetlink: add family parameter to Send, nl80211 integration test

genetlink/example_test.go
=> genetlink: add examples

conn_linux.go, conn_linux_test.go
=> netlink: fix large message handling on Linux

message.go
See: http://lxr.free-electrons.com/source/include/uapi/linux/netlink.h#L62.
=> netlink: fix value of HeaderFlagsAtomic

message.go, message_test.go
Much easier debugging to come with these.
=> netlink: add String methods to HeaderFlags and HeaderType

genetlink/family.go, genetlink/family_test.go
=> genetlink: add MulticastGroup type and parsing for Family

conn.go, conn_linux.go, conn_linux_integration_test.go, conn_others.go, conn_others_test.go, conn_test.go
=> netlink: add Conn.SetBPF for attaching BPF filters

genetlink/conn_linux_test.go
Interestingly, I wasn't able to get this one to fail with concurrency.  I put it in a loop and `go test` sent it a `SIGQUIT` after 10 minutes.  Maybe real netlink requests do the right thing.
=> genetlink: add concurrent integration test

conn_linux_test.go
I'll file a new issue about the sporadic `EINVAL` if it becomes a problem in CI.
Fixes #39 .
=> netlink: first pass at fix for TestLinuxConnIntegrationConcurrent

conn_others.go, conn_others_test.go
Noticed a small issue running `go get` on mac. This should fix it. :)
Cheers
=> Change dial() signature in conn_others following re-factoring

nlenc/int.go, nlenc/int_test.go
=> nlenc: add PutInt32, Int32Bytes

conn.go, nltest/nltest.go, nltest/nltest_linux_test.go, nltest/nltest_test.go
A first pass at a package that will allow testing netlink interactions without actually using netlink.
=> nltest: initial commit

nlenc/int.go, nlenc/int_test.go
This patch supports uint8 encoding and decoding functions in nlenc.
Fixes #65
=> support uint8 encoding and decoding in nlenc

conn.go, conn_linux.go, conn_linux_test.go, conn_test.go
Work in progress.  I have an integration test but it appears to make other tests fail.
Fixes #68 .
=> netlink: add Conn.ReadWriter to expose io.ReadWriter

message.go, message_test.go
Modified String() function. I have used the same string format as I have seen Flags printed in the strace output. Could not come up with a better one.
I have used missing Flags in a project, I could simply define them in there but I believe they belong in this package.
=> Added missing new object HeaderFlags.

conn.go, conn_linux.go, conn_linux_test.go
=> netlink: by default, lock OS thread internally

conn.go
=> receive iterative implement instead recursive

attribute_test.go, conn_linux_error_test.go, message_test.go, nlenc/endian.go
Fixes #77 .
@pgier If you could give this a go on your s390x machines before I merge, that'd be great!
=> netlink, nlenc: skip some tests on big-endian systems

conn.go, conn_linux.go, conn_linux_error_test.go, conn_test.go, nltest/nltest.go, nltest/nltest_linux_test.go, nltest/nltest_test.go
=> Implement SendMessages for sending batches

conn.go, conn_linux.go, conn_linux_test.go, conn_others.go, conn_others_test.go, conn_test.go
=> netlink: add ConnOption type and Conn.SetOption method

conn_linux.go, conn_linux_test.go
=> netlink: return EBADF on socket calls after Linux conn closed

conn.go, conn_linux_test.go, conn_test.go
=> netlink: add Conn.SyscallConn method

attribute.go
This is a breaking change for @florianl's go-conntrack, but it appears both occurrences can be changed to call MarshalAttributes or use the new AttributeEncoder as appropriate:
https://sourcegraph.com/github.com/florianl/go-conntrack@e8ae8c062940a33c82fedc7d2bc105b812c40e3f/-/blob/nest.go#L19:15
https://sourcegraph.com/github.com/florianl/go-conntrack@e8ae8c062940a33c82fedc7d2bc105b812c40e3f/-/blob/nest.go#L46
@florianl let me know if you have any big objections to me merging this.
My intent is to do this so I can further optimize Marshal/UnmarshalAttributes and the encoder/decoder without worrying about breaking people.
=> netlink: remove exported Attribute marshal and unmarshal binary methods

conn_linux_error_test.go, message.go
=> netlink: only check for errors with header type error

attribute.go, attribute_test.go
Signed-off-by: Lehner Florian <dev@der-flo.net>
This PR addresses the issue mentioned in https://github.com/mdlayher/netlink/issues/117.
=> Unmarshal unaligned attributes

conn.go, conn_linux.go, conn_linux_error_test.go, conn_linux_integration_test.go, conn_linux_test.go, errors.go, errors_linux_test.go, message.go, message_test.go, netns_linux.go, nltest/errors_others.go, nltest/errors_unix.go, nltest/nltest.go, nltest/nltest_linux_test.go, nltest/nltest_test.go, rawconn_lt_1.12.go
=> netlink: introduce OpError type, use throughout

conn_linux.go
Use SOCK_CLOEXEC when calling socket(2). This avoids races between
one goroutine calling socket(2) and another performing fork + exec,
which could otherwise result in the child process inheriting an
unexpected netlink socket file descriptor.
Fixes #137.
Signed-off-by: Andrei Tudor Călin <mail@acln.ro>
=> netlink: use SOCK_CLOEXEC when creating socket file descriptors

conn.go, conn_linux.go
An alternative to #141, for https://github.com/WireGuard/wgctrl-go/issues/58.
If no network namespace is set, make a best effort to switch to the calling thread's namespace anyway. If the caller has permission, it works. If they don't, nothing happens.
If the caller explicitly sets a namespace and they do not have permission, an error is returned.
=> netlink: best effort switching to calling thread's network namespace

attribute.go, attribute_test.go, example_attributedecoder_test.go, example_attributeencoder_test.go, message.go
=> netlink: add Nested method on Attribute{Decoder,Encoder}

README.md
=> netlink: v1.0.0

CHANGELOG.md, README.md
=> CHANGELOG: initial commit

conn_linux.go, conn_linux_integration_test.go
I believe this will fix #162, but I would appreciate a careful review to make sure I'm not missing anything.
/cc @acln0 and @libesz @bradfitz @MXWXZ who have run into this bug
=> netlink: Conn.Close unblocks Conn.Receive

.github/workflows/linux-integration-test.yml, .github/workflows/linux-test.yml, .github/workflows/static-analysis.yml
=> .github: port CI build to Actions

.github/workflows/linux-integration-test.yml, .github/workflows/linux-test.yml, .github/workflows/static-analysis.yml
PR for the issue: https://github.com/mdlayher/netlink/issues/180 .
=> netlink: updated github/workflow actions' versions

README.md
Add NETLINK_SOCK_DIAG to the ecosystem.
=> README: update Ecosystem
