mdlayher/netlink

.travis.yml

This way we can verify that `*_others.go` isn't broken when changes are made.

travis: test on OSX and Linux

---

align.go
attribute.go
attribute_test.go

Works as intended for marshaling and unmarshaling a slice of Attributes to and from a generic netlink "get family" request.

attribute: initial commit

---

attribute.go
conn_linux_test.go
message.go
nlenc/doc.go
nlenc/int.go
nlenc/int_test.go

These functions are unrelated to netlink sockets, so I think it's best to move them to another package and add additional functions there, like string/bytes encoding and maybe even attributes later.

nlenc: initial commit, move integer encoding/decoding functions

---

nlenc/int.go
nlenc/int_test.go

This occurs frequently enough that @jsimonetti even made helpers for it in his `rtnetlink` package.  I use it a lot as well, so let's just put it in `nlenc` and be done with it.

nlenc: add Uint{16,32,64}Bytes helpers

---

conn.go
conn_linux.go
conn_linux_test.go
conn_others.go
conn_others_test.go
conn_test.go
sockopt_linux.go
sockopt_linux_386.go
sockopt_linux_386.s

Borrowed the `setsockopt()` magic from my raw sockets project.  Seems to work fine on Linux.  Thinking about doing an integration test but I didn't like how it went when I tried to integrate it into our existing one.  I'm sure we'll come up with something.
Fixes #29 .

netlink: add {Join,Leave}Group using setsockopt on Linux

---

genetlink/conn.go
genetlink/conn_test.go

Not a whole lot to test here at the moment.  Need to do some better integration tests with multicast groups in the future.

genetlink: add Conn.{Join,Leave}Group

---

conn_linux.go
conn_linux_test.go
sockopt_linux.go

netlink: move from syscall to golang.org/x/sys/unix, where possible

---

conn.go
conn_linux.go
conn_linux_test.go
conn_test.go

Simplifies things, and removes some complicated logic and tests.  Double win.

netlink: use getsockname to assign Conn PID

---

conn.go
conn_test.go

To better facilitate plugging in an `osConn` from `nltest`.

netlink: make some osConn methods optional

---

attribute.go
attribute_test.go

Hi, I've added three helpers to `Attribute` including some tests. These are all exported to allow eg. NetFilter to make use of them, which should be their main purpose IMO. They're not implemented as struct members to avoid having to change (and bloat) the struct.
- IsNested() - masks leftmost bit
- IsNetByteOrder() - masks second leftmost bit
- GetType() - masks all other bits from the Type
I have benched using pointer receivers for these, but there was no perceivable performance difference. Let me know what you think!
T

Attribute helpers for nesting, endianness and a mask over .Type

---

attribute.go

Small change as discussed. I've left occurrences like `b[2:4]` untouched, since it's clear we're dealing with a slice range.
Not sure if the changes to the `case`s are for the better.

Use nlaHeaderLen instead of magic nr. 4

---

conn_linux_test.go

Recent kernel versions return the NLM_F_ROOT (0x100) header flag.
I'm not sure if this is the right fix for this, but this test currently fails on recent distributions (Fedora 27 and Ubuntu 18.04) because the header section of the message contains the NLM_F_ROOT flag (256/0x100).

update TestLinuxConnIntegration for recent kernel versions

---

nlenc/int_test.go

Skip int_tests on big endian systems

nlenc: skip some tests on big-endian systems

---

attribute.go
attribute_test.go

I haven't seen a netlink message yet that actually uses these, and since nested attributes in particular appear all the time without this flag being set, it doesn't seem to provide any added value.
For the time being, let's remove these.

netlink: remove Nested and NetByteOrder from Attribute

---

conn_others.go
conn_others_test.go

SendMessages() added to non-linux implementation of conn to match Socket interface. Some packages depending on netlink fail to build due to this since SendMessages method was merged in May 2018

fixes building on non-linux systems

---

bench_test.go

Before we look at optimizing anything, here's a base line.
```
✔ ~/src/github.com/mdlayher/netlink [mdl-attr-bench L|✚ 1…4] 
16:58 $ for i in `seq 1 5`; do go test -bench=. -run=NONE . >> before.bench; done
✔ ~/src/github.com/mdlayher/netlink [mdl-attr-bench L|✚ 1…5] 
17:00 $ cat before.bench 
goos: linux
goarch: amd64
pkg: github.com/mdlayher/netlink
BenchmarkMarshalAttributes/0-8          200000000                8.36 ns/op            0 B/op          0 allocs/op
BenchmarkMarshalAttributes/1-8          20000000                64.9 ns/op            24 B/op          3 allocs/op
BenchmarkMarshalAttributes/8-8           3000000               410 ns/op             320 B/op         10 allocs/op
BenchmarkMarshalAttributes/64-8           200000              6859 ns/op           14592 B/op …
```

netlink: add benchmarks for attribute handling

---

attribute.go
attribute_test.go
example_attributeencoder_test.go

The AttributeDecoder type makes it easy to quickly and safely decode
fields from netlink messages. Users, however, were left to use the
low-level functions to encode messages.
This CL introduces the AttributeEncoder type, which parallels the
AttributeDecoder API, making it just as easy to encode netlink messages,
including nested attributes.

netlink: add AttributeEncoder type

---

conn_linux.go

@mdlayher This is my take on  #92, key points being executing `wg.Wait()` before the syscall worker's input channel is closed, and using a done channel to gracefully terminate the goroutine.
This also reduces the amount of touching points with the mutex, making it a bit easier to modify. 
`Close()` is now executed off-thread because there is no longer any risk of misrouting messages to the wrong socket, and because slapping a write lock around an invocation of `do()` will attempt a recursive lock.
This change set turned out a bit bigger than intended, but removes `defer` in the hot path. I'm not sold on `doErr`, it feels verbose, but can't think of another approach either.
Will make a follow-up for unblocking pending `Receive()`.

conn_linux - stop syscall worker gracefully

---

attribute.go
conn.go

Mostly going for consistency with other parts of the package; single letter names aren't generally as friendly.

netlink: exported API documentation cleanup

---

attribute.go
attribute_test.go

For symmetry with AttributeEncoder, adds a Bytes function to
AttriuteDecoder that copies the bytes to a new slice to avoid retaining
the original.

feat: add Bytes func to AttributeDecoder

---

conn_linux.go
conn_linux_test.go

Signed-off-by: Lehner Florian <dev@der-flo.net>
While working on florianl/go-nfqueue, I've noticed netlink messages from the kernel without correct alignment. Besides the alignment, these messages are fine and can be parsed without problem.
I've traced down this issue to `func (c *conn) Receive() ([]Message, error)` in `conn_linux.go`, where `syscall.ParseNetlinkMessage()` failed with `EINVAL`.
E.g. `n` for `Recvmsg(b, nil, unix.MSG_PEEK)` is 171, `n` for `Recvmsg(b, nil, 0)` is also 171 and `syscall.ParseNetlinkMessage(b[:n])` failed because `nlmAlignOf()` in `syscall/netlink_linux.go` returns 172.

Align nl message length

---

conn.go
conn_linux_integration_test.go

This enables and verifies:
- many concurrent calls to Send/Receive, relying on the kernel to deal with socket concurrency
- serialized calls to Execute, to verify that individual request/response pairs actually line up (the most common use case)
- Receive and other calls can always be unblocked by Close

netlink: serialize calls to Conn.Execute, lock in concurrency behaviors

---

conn.go
conn_linux.go

This is a little bit tricky.
A user has created an application which locks OS thread and enters its own network namespace before using `wgctrl.New()` to manipulate WireGuard devices in that namespace. Because wgctrl is backed by this package but provides no explicit tunable at the moment to enter a namespace via the netlink connection, it would seem the correct behavior is to automatically inherit the calling thread's network namespace in the new goroutine.
I'm not an expert on namespaces, but I believe this change to be backward compatible. The majority of callers who are not specifying NetNS today expect to inherit the network namespace of the calling process. This should account for that use case, as well as that of a caller who has manipulated the calling goroutine's thread into …

netlink: add CallingThreadNetNS to enter caller's network namespace

---

conn_linux.go
conn_linux_gteq_1.12_integration_test.go
export_linux_test.go
netns_linux.go

I was a little leery of directly opening files and passing back the file descriptor without managing the entire lifetime of the file (how long does it continue to live?), so I decided to evaluate things a bit more and see what I could come up with.
The netNS type is a wrapper around network namespace operations which hopefully makes things clear and makes the lifetime of these network namespace files easy to reason about.

netlink: add netNS type for network namespace manipulation

---

conn.go
conn_linux.go
conn_linux_test.go

Signed-off-by: Lehner Florian <dev@der-flo.net>
This PR adds support for the socket option NETLINK_EXT_ACK. 
https://lwn.net/Articles/719721/

Add socket option NETLINK_EXT_ACK

---

conn_linux.go
conn_linux_test.go
netns_linux.go

The `conn_linux.go` changes are required to make this testable, but this should do the trick.
Fixes #144.

netlink: support for systems with network namespaces disabled

---

conn.go
conn_linux.go
conn_linux_test.go

This is an implementation of the configuration option that will allow callers to 
define that the thread lock must be bypassed. 
See discussion here for details: https://github.com/mdlayher/netlink/issues/146

Provide configuration option for not locking go-routines to threads

---

attribute.go
attribute_test.go

Signed-off-by: Lehner Florian <dev@der-flo.net>
This PR adds the attribute type NLA_FLAG.
NLA_FLAG does not hold data. It is used in the net/tipc netlink family.

Add NLA_FLAG

---

attribute.go
attribute_test.go

Hi Matt,
As discussed yesterday, this patch contributes two things:
- adds `AttributeDecoder.TypeFlags()` that returns the Type with an inverted `attrTypeMask`
- inverts the call chain between `UnmarshalAttributes()` and `ad.Next()`
This change is motivated by https://github.com/ti-mo/conntrack/issues/13, as I'd like to expose a `netfilter.AttributeDecoder/Encoder` and `conntrack.AttributeDecoder/Encoder` interface all the way up the call chain. If done right, decoding a whole netlink message can be done with only a single allocation of each layer's `Attribute` type. :scream: 
It doesn't save much on the benches in the repo, because it decodes all attributes anyway, but it allows for large efficiency gains in downstream libraries. Because attributes can now be decoded opportunistically, …

Opportunistically decode attributes in AttributeDecoder

---

conn_linux.go

Per the tentative 1.14 release notes, we must be prepared to deal with EINTR on slow system calls, such as a blocking read waiting on a multicast group.
https://tip.golang.org/doc/go1.14#runtime
I'm pretty sure this is all we have to do, but I'd appreciate more eyes on this.

netlink: handle EINTR when checking for syscall readiness

---

conn_linux_integration_test.go
conn_linux_test.go
go.mod
go.sum

Bump golang.org/x/sys/unix to get the RTMGRP_* consts and use them.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

Use RTMGRP_* consts from x/sys/unix

---

conn_linux.go
conn_linux_test.go

(see issue #164 for a detailed explanation)
This PR allows users to use their privileges regarding buffer sizes: root and users with `CAP_NET_ADMIN` can ignore the system's limit on buffer sizes. Unprivileged users are not affected, there's a fallback. The testcase has been adjusted.
While I was working on this PR I noticed that the library has no method to read back the actual buffer size of the socket. I added these methods (`GetReadBuffer` and `GetWriteBuffer`) which are similar to their Write pendants.

Improve behaviour of SetReadBuffer / SetWriteBuffer

---

conn.go
conn_linux.go
conn_linux_integration_test.go
conn_linux_test.go
netns_linux_test.go

:wave: Back again with another controversial change. :smile: This aims to eliminate the bottleneck described in https://github.com/mdlayher/netlink/issues/154. This is the approach I described in https://github.com/mdlayher/netlink/issues/154#issuecomment-578045314. With the goal of dropping support for Go 1.11 and lower, this might be a good time to revisit.
To Do:
---
There are 2 elements at play here:
- The message misrouting discussed in http://lists.infradead.org/pipermail/libnl/2017-February/002293.html
With this change, I'd like to start spelunking older versions of the kernel and the Go runtime for this bug. @mdlayher are you positive the `TestIntegrationConnConcurrent*` family of tests is able to reproduce this? Can you remember which Go and kernel version you were using at the …

Reduce thread locking behaviour to dial phase only

---

conn_test.go
errors.go
message.go
message_linux_test.go

netlink: support for parsing extended acknowledgement errors

---

conn_linux_integration_test.go

On 32-bit architectures like armhf and i386, `math.MaxUint32` is bigger than the maximum value the signed 32-bit `int` can take. This causes the tests to fail to build:
```
conn_linux_integration_test.go:604:24: constant 4294967295 overflows int
FAIL	github.com/mdlayher/netlink [build failed]
```
So use `(*Rand) Uint32` instead which returns a pseudo-random 32-bit value as a `uint32`.

tests: Fix integer overflow on 32-bit architectures

---

conn.go
conn_linux.go
conn_linux_integration_test.go
conn_test.go

I think those could be useful for cases when users need to read the existing buffer size before modifying it

Expose socket ReadBuffer & WriteBuffer functions
